### ISSUE TITLE
[Home screen] Apply the room cells design 

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-android-v2#48]
In the room lists of the Home screen, Tchap displays differently the 2 kinds of room:
- the direct chat ("message direct")
![image](https://user-images.githubusercontent.com/8969772/116448943-eefc4d00-a859-11eb-8017-2ef087812b24.png)

   - rounded avatar with 1 padlock on the top right corner
   - at the bottom corner of the avatar, a led is used to display the presence of the contact (if online -> led is visible, else led is hidden)
   - The room name here is the display name of the Contact. This display name is split in 2 pieces (see the existing methods in Tchap v1: [getNameFromDisplayName](https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java#L164) and [getDomainFromDisplayName](https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/util/DinsicUtils.java#L180)
   - The last message of the discussion is displayed under the contact name
   - a potential badge is displayed on the right for missed notifications
   - under this badge the last message date/time is displayed (keep the element-android date format for the moment)
   - note: an icon (a crossed out bell, see below) may be displayed after the contact name if the notification are disabled on this room 

- the group chat ("salon")
![image](https://user-images.githubusercontent.com/8969772/116448987-fde2ff80-a859-11eb-9a3d-724997e559fe.png)
![image](https://user-images.githubusercontent.com/8969772/116449658-b1e48a80-a85a-11eb-88a3-7c58732c32b1.png)

   - hexagonal avatar with 1 icon on the top right corner (a padlock or the forum icon) - I will explain you in direct
   - The room name
   - an icon (a crossed out bell ) may be displayed after the room name if the notification are disabled on this room
   - The last message of the discussion is displayed under the room name, including the sender name (**without their domain**)
   - on the right a label mentions the room type: privé/externe/forum (this point required #58, I will explain you in direct)
   - a potential badge is displayed on the right for missed notifications
   - under this badge the last message date/time is displayed (keep the element-android date format for the moment) 
 
Note for both room type: a red exclamation mark is displayed if an action is expected from the user. This icon is displayed at the location of the notification badge, or in front of it.

See the "Page Conversations" in the design project

Note: In Tchap v1, the layout of these 2 kinds of room is handled [here](https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/adapters/TchapRoomAdapter.java#L95)
The type of the room is managed [here](https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/fr/gouv/tchap/adapters/TchapRoomAdapter.java#L71)
The way to populate the room cell in v1 is [here](https://github.com/dinsic-pim/tchap-android/blob/develop/vector/src/main/java/im/vector/adapters/RoomViewHolder.java#L126)

Some fixes to do are mentioned in this [issue](https://github.com/dinsic-pim/tchap-android-v2/issues/60)

**Comment by elghrabi** [comment]
Not to forget UI of pin room (small blue triangle in the top left)
